### PR TITLE
Fix terminal going offscreen in neovide in top/bottom/fullscreen

### LINKED ISSUE #3: Neoterm in vertical mode being off-screen in neovide GUI
Using the neovide GUI for nvim, the neoterm terminal will appear off to the right side of the viewport when opening neoterm in vertical mode. Both horizontal and fullscreen mode work fine.

### PR DESCRIPTION
**Pull request by dpi0**
When using neovide and using the top/bottom/fullscreen options, by default the terminal window goes offscreen. When a width of `1` or `100%` is used with right/center it also goes offscreen.

A simple solution was to subtract `width_padding` from each position's width.

Fixes #3

### CODE REVIEW

File: lua/neoterm.lua [hunk 1]
```diff
@@ -154,33 +154,35 @@ function neoterm.open(opts)
       border = "single",
     }
 
+    local width_padding = 2 -- Add some padding so that terminal fits within the visible area (neovide)
```
Comment (itmecho) [inline lua/neoterm.lua]: Given this seems to be a neovide specific issue, I think we can only do this for neovide users.
```suggestion
    -- Fix for neovide where the terminal ends up outside of the visible area
    local width_padding = vim.g.neovide and 2 or 0
```

**Review by itmecho — CHANGES_REQUESTED** [review]

File: lua/neoterm.lua (hunk 1 above)
Comment (dpi0) [reply lua/neoterm.lua]: fd70ef2cbca52148e7af38b005602ecdda7f539b will work with this great suggestion!

**Review by itmecho — APPROVED** [review]
Thank you for sorting that =]
